---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- statefulset.yml
- service.yml

images:
- name: elasticsearch
  newName: docker.io/saidsef/elasticsearch
  newTag: v2023.01

commonAnnotations:
  app.kubernetes.io/name: elasticsearch
  app.kubernetes.io/part-of: elasticsearch
