---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- statefulset.yml
- service.yml

images:
- name: elasticsearch
  newName: docker.io/saidsef/elasticsearch
  newTag: latest
- name: prometheus
  newName: docker.io/bitnami/elasticsearch-exporter
  newTag: 1.1.0