---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- statefulset.yml
- service.yml

images:
- name: elasticsearch
  newName: docker.io/saidsef/elasticsearch
  newTag: v2026.06

labels:
- pairs:
    app.kubernetes.io/name: elasticsearch
  includeSelectors: true
- pairs:
    app.kubernetes.io/instance: elasticsearch
    app.kubernetes.io/version: "6.8"
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: elasticsearch
    app.kubernetes.io/managed-by: kustomize
  includeSelectors: false
  includeTemplates: true
