---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  labels:
    name: elasticsearch
    app: elasticsearch
spec:
  serviceName: "elasticsearch"
  podManagementPolicy: "Parallel"
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        name: elasticsearch
        app: elasticsearch
    spec:
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      automountServiceAccountToken: false
      shareProcessNamespace: false
      terminationGracePeriodSeconds: 60
      enableServiceLinks: false
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: "kubernetes.io/hostname"
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: "kubernetes.io/arch"
                    operator: "In"
                    values:
                      - "amd64"
              weight: 1
      containers:
        - image: docker.io/saidsef/elasticsearch:v2023.01
          imagePullPolicy: Always
          name: elasticsearch
          ports:
            - protocol: TCP
              containerPort: 9200
              name: elasticsearch
            - protocol: TCP
              containerPort: 9300
              name: cluster
          lifecycle:
            preStop:
              exec:
                command:
                  - /usr/bin/curl
                  - -XPOST
                  - http://127.0.0.1:9200/_flush
          livenessProbe:
            tcpSocket:
              port: 9200
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              port: 9200
              path: _cat/health
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 5
          resources:
            requests:
              memory: "4Gi"
              cpu: "250m"
            limits:
              memory: "4Gi"
              cpu: "500m"
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            capabilities:
             drop:
               - ALL
             add:
               - NET_BIND_SERVICE
          volumeMounts:
            - name: storage
              mountPath: /usr/share/elasticsearch/data
              subPath: data
              readOnly: false
            - name: storage
              mountPath: /tmp
              subPath: tmp
              readOnly: false
      volumes:
        - name: storage
          emptyDir:
            sizeLimit: 3Gi
