name: Auto
on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed
  workflow_dispatch:

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - uses: hmarr/auto-approve-action@v2
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"

  auto-merge-pr:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Auto merge PR
      uses: actions/github-script@v4
      with:
        github-token: ${{ github.token }}
        script: |
          const pull_request_number = context.payload.number;

          await github.repos.merge({
            owner: context.repo.owner,
            repo: context.repo.repo,
          });