name: CI
on:
  push:
    branches:
      - main
    paths:
      - "Dockerfile"
      - "conf/**"
      - ".dockerignore"
  pull_request:
    branches:
      - main
    paths:
      - "Dockerfile"
      - "conf/**"
      - ".dockerignore"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Set Tag Name
      run: |
        echo "TAG=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV
        echo "DATE=v$(echo `date +'%Y.%m'`)" >> $GITHUB_ENV
    - name: Login to DockerHub
      uses: docker/login-action@v2 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker image - (TAG)
      uses: docker/build-push-action@v2
      env:
        DOCKER_BUILDKIT: 1
      with:
        context: .
        file: ./Dockerfile
        pull: true
        push: true
        tags: docker.io/saidsef/elasticsearch:${{ env.TAG == 'main' && 'latest' || env.TAG }}
    - name: Build and push Docker image - (DATE)
      uses: docker/build-push-action@v2
      if: ${{ contains(github.ref, 'master') }}
      env:
        DOCKER_BUILDKIT: 1
      with:
        context: .
        file: ./Dockerfile
        pull: true
        push: true
        tags: docker.io/saidsef/elasticsearch:${{ env.DATE }}
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: docker.io/saidsef/elasticsearch:${{ env.TAG == 'main' && 'latest' || env.TAG }}
        format: 'template'
        template: '@/contrib/sarif.tpl'
        output: 'trivy-results.sarif'
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: 'trivy-results.sarif'

  auto-approve:
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ github.event_name == 'pull_request' }}
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - uses: hmarr/auto-approve-action@v2
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"

  # auto-merge-pr:
  #   runs-on: ubuntu-latest
  #   if: ${{ github.event_name == 'pull_request' }}
  #   steps:
  #   - name: Check out repository code
  #     uses: actions/checkout@v3
  #   - name: Auto merge PR
  #     uses: actions/github-script@v4
  #     with:
  #       github-token: ${{ github.token }}
  #       script: |
  #         await github.repos.merge({
  #           owner: context.repo.owner,
  #           repo: context.repo.repo,
  #         });
