name: Test
on:
  workflow_run:
    workflows:
      - CI
    branches:
      - main
    types:
      - completed
    paths:
      - "deployment/*"
  workflow_dispatch:

jobs:
  k8s-test:
    runs-on: ubuntu-latest
    if: ${{ ! contains(github.ref, 'main') }}
    steps:
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.7.0
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run K8s test
        run: |
          kubectl cluster-info
          export NS=`cat deployment/kustomization.yml  | grep namespace | awk '{ print $2 }'`
          if [ -z "$NS" ]; then
            export NS='storage'
          fi
          kubectl create namespace $NS
          kubectl kustomize deployment/ | kubectl apply -n $NS -f - 
          kubectl get all -n $NS